name: svc-coffee-api

on:
  push:
    branches:
      - main
      - dev
      - hom
    paths-ignore:
      - ".github/**"s

jobs:
  runs-on: ubuntu-latest
  name: ğŸ« Config enviroments credentias

  step:
      - name: ğŸ”„ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ”’ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_ACCOUNT_REGION}}

    - name: â¬‡ï¸ Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ğŸ› ï¸ Build project
      run: cd app && npm run build && cd ../ && npm run build

       - name: ğŸ¥¾ CDK Bootstrap
        timeout-minutes: 15
        run: cdk bootstrap aws://883183666441/us-east-1 --force
      
      - name: âœ… Cdk synth
      run: cdk synth

      - name: ğŸš€ Cdk deploy
      run: |
      DEPLOY_OUTPUT=$(cdk deploy --require-approval never)

